services:
  postgres:
    image: postgres
    container_name: planedo_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=planedo_development
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
